#!/usr/bin/env python3
"""
One-off generator (NOT part of the main codegen pipeline in helper/codegen/): reads the
vendored D3 bundle and the D3 interactive report template from misc/STC-experiments/, and
emits src/tox_stc_html_assets.F90, a generated (never hand-edited) Fortran module holding
their content as compile-time character parameters -- so the resulting Fortran/C/Python/R
binary/package never needs to locate these files at runtime; they are baked in.

Run: python3 helper/embed_stc_html_assets.py
Re-run this whenever misc/STC-experiments/vendor/d3.v7.min.js or
misc/STC-experiments/interactive_template.html change (e.g. a D3 version bump) -- the
generated .F90 file is committed, like everything under src/generated/.

Why compile-time embedding, not a runtime-read external file: this content ships inside
Tensor Omics regardless of delivery shape (a bare Fortran+C executable, a Python wheel, an R
package) -- runtime path resolution (relative to argv[0], an installed package's own data
directory, an environment variable, ...) is a different, fragile answer per delivery
mechanism. Baking the content into the compiled artifact itself sidesteps that class of
problem entirely: there is nothing to "find" at runtime.

Why a hand-rolled generator instead of e.g. a C `xxd -i`-style .inc: this needs to become a
valid Fortran CHARACTER parameter, quote-escaped, chunked to stay under this build's
practical free-form line-length limit (empirically well under 16000 chars/line, comfortably
safe at the ~90-char raw chunks / 3-chunks-per-line grouping used below -- see the commit
introducing this file for the exact experiment), and with literal newlines represented via
achar(10) rather than embedded raw in the generated source (a raw newline byte inside a
Fortran string literal would terminate the *generated source's own* line, corrupting it).
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)

D3_PATH = os.path.join(REPO_ROOT, "misc", "STC-experiments", "vendor", "d3.v7.min.js")
TEMPLATE_PATH = os.path.join(REPO_ROOT, "misc", "STC-experiments", "interactive_template.html")
OUT_PATH = os.path.join(REPO_ROOT, "src", "tox_stc_html_assets.F90")

D3_PLACEHOLDER = "__STC_D3_JS__"
DATA_PLACEHOLDER = "__STC_DATA__"

RAW_CHUNK_SIZE = 90
CHUNKS_PER_LINE = 3
INDENT = " " * 8


def fortran_literal_pieces(text):
    """Split `text` into a flat sequence of Fortran expression pieces (each either a quoted
    string literal or the expression achar(10)) that, concatenated with `//`, reproduce
    `text` exactly. Newlines are extracted first and represented as achar(10) so no chunk
    ever contains a raw newline byte (which would break the *generated* source line)."""
    pieces = []
    lines = text.split("\n")
    for i, line in enumerate(lines):
        for start in range(0, len(line), RAW_CHUNK_SIZE):
            raw_chunk = line[start:start + RAW_CHUNK_SIZE]
            escaped = raw_chunk.replace("'", "''")
            pieces.append("'" + escaped + "'")
        if i < len(lines) - 1:
            pieces.append("achar(10)")
    if not pieces:
        pieces.append("''")
    return pieces


def render_parameter(name, text):
    pieces = fortran_literal_pieces(text)
    lines = [f"    character(len=*), parameter :: {name} = &"]
    for i in range(0, len(pieces), CHUNKS_PER_LINE):
        group = pieces[i:i + CHUNKS_PER_LINE]
        is_last = (i + CHUNKS_PER_LINE >= len(pieces))
        joined = "//".join(group)
        suffix = "" if is_last else "//&"
        lines.append(INDENT + joined + suffix)
    return "\n".join(lines)


def main():
    with open(D3_PATH, "r", encoding="utf-8") as fh:
        d3_js = fh.read()
    with open(TEMPLATE_PATH, "r", encoding="utf-8") as fh:
        template = fh.read()

    if D3_PLACEHOLDER not in template:
        raise ValueError(f"{TEMPLATE_PATH} is missing the {D3_PLACEHOLDER} placeholder")
    if DATA_PLACEHOLDER not in template:
        raise ValueError(f"{TEMPLATE_PATH} is missing the {DATA_PLACEHOLDER} placeholder")

    head, rest = template.split(D3_PLACEHOLDER, 1)
    mid, tail = rest.split(DATA_PLACEHOLDER, 1)

    parts = [
        render_parameter("REPORT_TEMPLATE_HEAD", head),
        render_parameter("REPORT_TEMPLATE_MID", mid),
        render_parameter("REPORT_TEMPLATE_TAIL", tail),
        render_parameter("D3_JS", d3_js),
    ]

    out = (
        "!> Generated by helper/embed_stc_html_assets.py from\n"
        "!| misc/STC-experiments/vendor/d3.v7.min.js and\n"
        "!| misc/STC-experiments/interactive_template.html. Do not edit -- regenerate instead.\n"
        "!|\n"
        "!| The interactive HTML report is assembled by writing, in order:\n"
        "!| REPORT_TEMPLATE_HEAD, D3_JS, REPORT_TEMPLATE_MID, <the run's JSON payload>,\n"
        "!| REPORT_TEMPLATE_TAIL -- see tox_stc_json::write_stc_interactive_html_report.\n"
        "module tox_stc_html_assets\n"
        "    implicit none\n"
        "\n"
        "    private\n"
        "    public :: REPORT_TEMPLATE_HEAD, REPORT_TEMPLATE_MID, REPORT_TEMPLATE_TAIL, D3_JS\n"
        "\n"
        + "\n\n".join(parts) + "\n"
        "\n"
        "end module tox_stc_html_assets\n"
    )

    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(out)
    print(f"[embed_stc_html_assets] wrote {OUT_PATH} ({len(out) / 1024:.0f} KB source, "
          f"D3 {len(d3_js)} bytes, template {len(template)} bytes)")


if __name__ == "__main__":
    main()
