stages:
  - run-tests
  - generate-docs

image: archlinux:latest
before_script:
  # install gfortran, python, pip, git
  - pacman -Sy --noconfirm archlinux-keyring
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm gcc-fortran python python-pip git
  - pacman -Scc --noconfirm

  # install fpm
  - curl -L --output /usr/local/bin/fpm https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
  - chmod a+x /usr/local/bin/fpm

  # install ford
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install --upgrade pip
  - pip install ford

  # set up git
  - git config --global user.email "ci-bot@yourdomain.com"
  - git config --global user.name "CI Bot"
  - git remote set-url origin @gitlab.com/your-namespace/your-project.git
  - |
    function git-push() {
      git add -f "${@:2}"
      git commit -m "$1 [skip ci]" || echo "No changes to commit"
      git push https://oauth2:${JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:$CI_COMMIT_BRANCH
    }

  # show versions
  - echo "Versions:"
  - python --version
  - pip --version
  - ford --version
  - gfortran --version

run-tests:
  stage: run-tests
  rules:
    # trigger when pushing to main directly, but only if src/ or test/ changed
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - src/**
        - test/**
        - test_runner.sh
      when: always

    # trigger only when a MR to 'main' is created and src/ or test/ changed
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      changes:
        - src/**
        - test/**
        - test_runner.sh
      when: always

    # prevent running on other branches outside MR context
    - when: never

  script:
    # install ifx
    - curl https://registrationcenter-download.intel.com/akdlm/IRC_NAS/466b0d65-e502-4172-9e06-24c565029b96/intel-fortran-compiler-2025.2.1.9_offline.sh -o install_ifx.sh
    - bash install_ifx.sh -a -s --eula accept
    - source /opt/intel/oneapi/setvars.sh

    # run tests using ifx
    - echo Run tests with ifx
    - FC=ifx bash test_runner.sh
    - echo Run tests with gfortran

    # run tests using gfortran
    - bash test_runner.sh


generate-docs:  # generate documentation after tests have passed
  stage: generate-docs
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - src/**
        - test/**
        - ford.yml
      when: always
    - when: never
  needs:
    - job: run-tests
      optional: true  # if ford.yml was changed, the test stage does not exist in the pipeline
  script:
    # generate docs
    - ford ford.yml
    - echo "generated documentation successfully"

    # add and commit changes to docs folder
    - git-push "Update generated documentation" doc
