stages:
  - run-tests
  - generate-docs
  - done

image: archlinux:latest

.install-r: &install-r
  - pacman -S --noconfirm r make
  - pacman -Scc --noconfirm
  - R --version
  # install Rcpp, readr
  - Rscript -e 'install.packages("Rcpp", repos="https://cloud.r-project.org")'
  - Rscript -e 'installed.packages()[, c("Package", "Version")]'

.install-python: &install-python
  - pacman -S --noconfirm python python-pip
  - pacman -Scc --noconfirm
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install --upgrade pip
  - pip install numpy pandas
  - pip list
  - python --version
  - pip --version

.install-fortran: &install-fortran
  - pacman -S --noconfirm gcc-fortran libzip xxhash
  - pacman -Scc --noconfirm
  # install fpm
  - curl -L --output /usr/local/bin/fpm https://github.com/fortran-lang/fpm/releases/download/v0.12.0/fpm-0.12.0-linux-x86_64-gcc-12
  - chmod a+x /usr/local/bin/fpm
  - gfortran --version

  # install ifx
  - curl https://registrationcenter-download.intel.com/akdlm/IRC_NAS/724303ca-6927-4327-a560-e0aabb55b010/intel-fortran-compiler-2025.3.1.16_offline.sh -o install_ifx.sh
  - bash install_ifx.sh -a -s --eula accept
  - source /opt/intel/oneapi/setvars.sh
  - ifx --version

.install-git: &install-git
  - pacman -S --noconfirm git
  - pacman -Scc --noconfirm
  # set up git
  - git config --global user.email "ci-bot@yourdomain.com"
  - git config --global user.name "CI Bot"
  - |
    function git-push() {
      git add -f "${@:2}"
      git commit -m "$1 [skip ci]" || echo "No changes to commit"
      git push https://oauth2:${JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git HEAD:$CI_COMMIT_BRANCH
    }

before_script:
  # update system
  - pacman -Sy --noconfirm archlinux-keyring
  - pacman -Syu --noconfirm

run-tests:
  stage: run-tests
  rules:
    # trigger only when a MR or commit to 'main'
    - if: '$CI_COMMIT_BRANCH == "main" || ($CI_PIPELINE_SOURCE == "merge_request_event")'
      changes:
        - rcpp/**
        - python/**
        - src/**
        - test/**
        - test_runner.sh
        - build.sh
        - build_utils.sh

    # prevent running on other branches outside MR context
    - when: never

  script:
    - *install-fortran
    - *install-r
    - *install-python

    - |
      for compiler in ifx gfortran; do
        FC=$compiler bash test_runner.sh
        for i in rcpp/test/*.[rR]; do echo ; echo $i ; Rscript $i ; done
        for i in python/test/*.py; do echo ; echo $i ; python $i ; done
      done

generate-docs:  # generate documentation after tests have passed
  stage: generate-docs
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - src/**
        - ford.yml
    - when: never
  needs:
    - job: run-tests
      optional: true  # if ford.yml was changed, the test stage does not exist in the pipeline
  script:
    # install ford
    - *install-python
    - pip install ford
    - ford --version

    # generate docs
    - ford ford.yml
    - echo "generated documentation successfully"

    # add and commit changes to docs folder
    - *install-git
    - git-push "Update generated documentation" doc

done: # Final stage that will always be in a pipeline and succeeds when all other stages pass
  stage: done
  needs:
    - job: run-tests
      optional: true
    - job: generate-docs
      optional: true
  script:
    - echo "All jobs passed"
