name: 'Install Fortran'
description: 'Installs all requirements to compile the Fortran code, meaning the compiler, needed libraries and the Fortran Package Manager'

inputs:
  compiler:
    description: 'Fortran compiler to install (gfortran, ifx)'
    required: true
    default: gfortran

runs:
  using: "composite"
  steps:
    - name: Install Intel compiler ifx
      if: ${{ inputs.compiler == 'ifx' }}
      shell: bash
      run: |
        pacman -Sy --needed --noconfirm gcc  # ifx needs some libs from gcc
        pacman -Scc --noconfirm
        curl https://registrationcenter-download.intel.com/akdlm/IRC_NAS/176ca159-bee8-44f2-9164-db26f95de382/intel-fortran-compiler-2026.0.0.573_offline.sh -o install_ifx.sh
        bash install_ifx.sh -a -s --eula accept
        rm install_ifx.sh
        echo source /opt/intel/oneapi/setvars.sh >> ~/tox_init.sh
        echo ifx --version >> ~/tox_init.sh

    - name: Install GNU compiler gfortran
      if: ${{ inputs.compiler == 'gfortran' }}
      shell: bash
      run: |
        pacman -Sy --needed --noconfirm gcc-fortran
        pacman -Scc --noconfirm
        echo gfortran --version >> ~/tox_init.sh

    - name: Install needed libraries and dependencies used in TensorOmics
      shell: bash
      run: |
        pacman -Sy --needed --noconfirm which  # 'which' needed in build script
        pacman -Sy --needed --noconfirm libzip xxhash
        pacman -Scc --noconfirm

    - name: Install fpm
      shell: bash
      run: |
        curl -L --output /usr/local/bin/fpm https://github.com/fortran-lang/fpm/releases/download/v0.13.0/fpm-0.13.0-linux-x86_64-gcc-12
        chmod a+x /usr/local/bin/fpm

    - name: Show versions
      shell: bash
      run: source ~/tox_init.sh
