name: 'Install Fortran'
description: 'Installs all requirements to compile the Fortran code, meaning the compiler, needed libraries and the Fortran Package Manager'

inputs:
  compiler:
    description: 'Fortran compiler to install (gfortran, ifx)'
    required: true
    default: gfortran

runs:
  using: "composite"
  steps:
    - name: Install Intel compiler ifx and icx
      if: ${{ inputs.compiler == 'ifx' }}
      shell: bash
      run: |
        pacman -Sy --needed --noconfirm gcc g++  # ifx needs some libs from gcc, icx some of g++
        pacman -Scc --noconfirm
        for i in e5d4469d-33c1-4d48-8b45-48de1e6fb9e9/intel-dpcpp-cpp-compiler-2026.1.1.22.sh 09a1aab3-8441-4a4e-a243-1c1c8e15598c/intel-fortran-compiler-2026.1.1.19.sh
        do
          curl https://registrationcenter-download.intel.com/akdlm/IRC_NAS/$i -o install_compiler.sh
          bash install_compiler.sh -a -s --eula accept
          rm install_compiler.sh
        done
        source /opt/intel/oneapi/setvars.sh
        env | grep oneapi >> $GITHUB_ENV

    - name: Install GNU compiler gfortran
      if: ${{ inputs.compiler == 'gfortran' }}
      shell: bash
      run: |
        pacman -Sy --needed --noconfirm gcc-fortran
        pacman -Scc --noconfirm

    - name: Install needed libraries and dependencies used in TensorOmics
      shell: bash
      run: |
        pacman -Sy --needed --noconfirm libzip xxhash
        pacman -Scc --noconfirm

    - name: Install fpm
      shell: bash
      run: |
        curl -L --output /usr/local/bin/fpm https://github.com/fortran-lang/fpm/releases/download/v0.13.0/fpm-0.13.0-linux-x86_64-gcc-12
        chmod a+x /usr/local/bin/fpm

    - name: Show version for reproducibility
      shell: bash
      run: ${{ inputs.compiler }} --version
