# =============================================================================
# Correctness check for the pure-C marshalling of the awkward types (strings and
# int-logicals <-> Fortran c_bool / fixed-width char), via serde round-trips.
#
#   - C round-trip: C serialize -> C deserialize recovers the input (through the
#     real, trusted Fortran serde core).
#   - Cross-check:  the EXISTING Rcpp deserializer reads what the C serializer
#     wrote, proving the C buffers are byte-compatible with the established path
#     (rules out a symmetric in/out marshalling bug).
#
# Run from anywhere:   Rscript misc/bench_rcpp_cpp11/serde_check.R
# =============================================================================

options(warn = 1)

.args      <- commandArgs(trailingOnly = FALSE)
.file_arg  <- sub("^--file=", "", .args[grep("^--file=", .args)])
script_dir <- if (length(.file_arg)) dirname(normalizePath(.file_arg)) else normalizePath(".")
repo_root  <- normalizePath(file.path(script_dir, "..", ".."))
build_dir  <- file.path(repo_root, "build")
rcpp_src   <- file.path(repo_root, "rcpp", "tensor_omics", "src")
stopifnot(file.exists(file.path(build_dir, "libtensor-omics.so")))

pkg_libs <- sprintf("-L%s -Wl,-rpath,%s -ltensor-omics", shQuote(build_dir), shQuote(build_dir))
Sys.setenv(PKG_LIBS = pkg_libs)
rbin <- file.path(R.home("bin"), "R")

## ---- compile the pure-C serde shim -----------------------------------------
cat("Compiling pure-C serde shim (R CMD SHLIB) ...\n")
if (system(sprintf("cd %s && %s CMD SHLIB serde_c.c -o serde_c.so",
                   shQuote(script_dir), shQuote(rbin))) != 0)
    stop("serde_c compile failed")
dyn.load(file.path(script_dir, "serde_c.so"))

c_ser_lgl <- function(arr, f)          .Call("serialize_logical_ccall", arr, f)
c_des_lgl <- function(shape, f)        .Call("deserialize_logical_ccall", as.integer(shape), f)
c_ser_chr <- function(arr, f)          .Call("serialize_char_ccall", arr, f)
c_des_chr <- function(strlen, shape, f).Call("deserialize_char_ccall",
                                             as.integer(strlen), as.integer(shape), f)

## ---- compile the Rcpp deserializers for the cross-check --------------------
cat("Compiling Rcpp deserialize shims (cross-check) ...\n")
Sys.setenv(PKG_CPPFLAGS = sprintf("-I%s", shQuote(rcpp_src)))
Rcpp::sourceCpp(file.path(rcpp_src, "f42_serde_arrays_deserialize_logical.cpp"))
Rcpp::sourceCpp(file.path(rcpp_src, "f42_serde_arrays_deserialize_char.cpp"))

## ---- tiny test harness ------------------------------------------------------
.pass <- 0L; .fail <- 0L; .log <- character(0)
check <- function(desc, cond) {
    ok <- isTRUE(cond)
    if (ok) .pass <<- .pass + 1L else .fail <<- .fail + 1L
    .log <<- c(.log, sprintf("- %s %s", if (ok) "PASS" else "FAIL", desc))
    cat(sprintf("  %s  %s\n", if (ok) "PASS" else "FAIL", desc))
}

cat("\n== logical (int-logical <-> c_bool byte) ==\n")
arrL <- matrix(c(TRUE, FALSE, TRUE, FALSE, TRUE, FALSE), nrow = 2)   # 2x3, asymmetric
fL   <- tempfile()
check("serialize returns ierr == 0", identical(c_ser_lgl(arrL, fL), 0L))
rt   <- c_des_lgl(dim(arrL), fL)
check("C round-trip recovers values + dim", identical(rt$arr, arrL))
xr   <- .deserialize_logical_helper_rcpp(as.integer(dim(arrL)), fL)
check("Rcpp reads what C wrote (byte-compat)", identical(xr$arr, arrL))

cat("\n== character (R strings <-> fixed-width column-major char) ==\n")
arrC <- c("a", "bbb", "cc", "dddd")                                 # varying lengths -> padding
fC   <- tempfile()
check("serialize returns ierr == 0", identical(c_ser_chr(arrC, fC), 0L))
sl   <- max(nchar(arrC))
rt   <- c_des_chr(sl, length(arrC), fC)
check("C round-trip recovers strings", identical(as.vector(rt$arr), arrC))
xr   <- .deserialize_char_helper_rcpp(as.integer(sl), as.integer(length(arrC)), fC)
check("Rcpp reads what C wrote (byte-compat)", identical(as.vector(xr$arr), arrC))

arrC2 <- matrix(c("xx", "y", "zzz", "w", "vv", "uuuu"), nrow = 2)    # 2x3 string matrix
fC2   <- tempfile()
invisible(c_ser_chr(arrC2, fC2))
rt2   <- c_des_chr(max(nchar(arrC2)), dim(arrC2), fC2)
check("C round-trip recovers 2D string matrix", identical(rt2$arr, arrC2))

cat(sprintf("\nSummary: %d passed, %d failed\n", .pass, .fail))

## ---- self-documenting report -----------------------------------------------
md <- c(
    "# Pure-C `.Call` marshalling check — strings & logicals",
    "",
    sprintf("_Generated by `serde_check.R` on %s (R %s)._", Sys.Date(), getRversion()),
    "",
    "The two conversions the Rcpp path centralises in `tox_marshal.h` — R's",
    "int-logicals <-> Fortran `c_bool` bytes, and R strings <-> Fortran fixed-width",
    "column-major char buffers — reimplemented in **pure C** with `R_alloc`'d",
    "transient buffers (auto-freed on return; nothing to leak on an error longjmp).",
    "Verified two ways through the real Fortran serde core:",
    "",
    "- **round-trip**: C serialize -> C deserialize recovers the input;",
    "- **cross-check**: the existing Rcpp deserializer reads what the C serializer",
    "  wrote (byte-compatible with the established path — rules out a symmetric bug).",
    "",
    .log,
    "",
    sprintf("**Summary: %d passed, %d failed.**", .pass, .fail),
    "",
    "Takeaway: no C++ is needed for the awkward types. `c_bool` output is read as",
    "`unsigned char != 0` (ifx writes `0xFF`); strings use `max_strlen` fixed-width,",
    "column-major, zero-padded slots, recovered up to the first `NUL`.",
    ""
)
writeLines(md, file.path(script_dir, "SERDE_CHECK.md"))
cat("Wrote", file.path(script_dir, "SERDE_CHECK.md"), "\n")

if (.fail > 0L) quit(status = 1L)
